### ISSUE TITLE
The following binaries use incompatible versions of Swift

### ISSUE THREAD

**Issue by Boom2112** [Bluedot-Innovation/PointSDK-iOS#1]
error: The following binaries use incompatible versions of Swift:
Library/Developer/Xcode/DerivedData/PointSDK-MinimalIntegrationExample-iOS-ffiuzrndppautrchtipvmpjgbzqr/Build/Products/Debug-iphonesimulator/PointSDK Swift Minimal.app/Frameworks/BDPointSDK.framework/BDPointSDK
Library/Developer/Xcode/DerivedData/PointSDK-MinimalIntegrationExample-iOS-ffiuzrndppautrchtipvmpjgbzqr/Build/Products/Debug-iphonesimulator/PointSDK Swift Minimal.app/PointSDK Swift Minimal

xCode version: 10.2

**Comment by poborin** [comment]
Hi @Boom2112 ,

The current version of the PointSDK is not compatible with the Xcode 10.2. However, we are currently working on the compatibility build and it will be released soon.

Our product is a commercial product and you need to have a fully paid account and valid API key to make it work. You can request further help at [help@bluedot.io](mailto:help@bluedot.io) or request a free demo at [https://bluedot.io/demo](https://bluedot.io/demo)

Thanks for your interest in our product.
