### ISSUE TITLE
Crash when starting app - source seems to be from this SDK

### ISSUE THREAD

**Issue by darylteo** [Bluedot-Innovation/PointSDK-iOS#13]
Hi, we are using the SwrveGeoSDK which has a dependency on BluedotPointSDK (current version in use is 15.5.0).

After issuing an update for our app our beta testers are reporting that the App crashes immediately on boot. After tracking down the crash logs, it seems that it is linked to this call from the BDPointSDK. 

![Screen Shot 2022-08-17 at 8 37 36 pm](https://user-images.githubusercontent.com/1226920/185102661-a0ebdc4e-d402-4da1-adef-72c991e2ad1a.jpg)

Do you have any ideas why this may be happening? And would upgrade to the latest SDK fix the issue? I didn't see any mention of this in previous releases so not sure if this is a resolved bug.

**Comment by toroduque** [comment]
Hey @darylteo,

Thanks for reaching out. We recommend checking this issue with Swrve directly. We don’t have any active account with Swrve, so they probably have to remove our Point SDK from their SwrveGeoSDK.

Cheers!
