### ISSUE TITLE
Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by flyric123** [Bluedot-Innovation/PointSDK-iOS#2]
After we integrated the SDK into out project (just included the framework, no codes to call any functions in the SDK), we keep having crashes because of the following errors:
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/nei/Library/Developer/CoreSimulator/Devices/14AC942A-66F8-479F-81A6-8881786BD893/data/Containers/Bundle/Application/8F33CA62-FC14-4F71-8815-4327868925C2/PGPlugin.app/Frameworks/BDPointSDK.framework/BDPointSDK
  Reason: image not found

Any ideas?

XCode version: 10.2.1
MacOS version: 10.14.4
Simulator version: iphone 8 on iOS 12.2

**Comment by poborin** [comment]
Hi @flyric123 ,

The current version of the PointSDK is not compatible with the Xcode 10.2. However, we are currently working on the compatibility build and it will be released soon.

Our product is a commercial product and you need to have a fully paid account and valid API key to make it work. You can request further help at help@bluedot.io or request a free demo at https://bluedot.io/demo

Thanks for your interest in our product.

**Comment by andrew-stirling** [comment]
The latest release (1.13.3: https://cocoapods.org/pods/BluedotPointSDK) is now compatible with Xcode 10.2. Please update to that version and let us know if you continue to have issues.
