### ISSUE TITLE
BluedotPointSDK is still point to 15.0.0

### ISSUE THREAD

**Issue by rezakhmf** [Bluedot-Innovation/PointSDK-iOS#3]
when I try to install your sdk through cocoapod is still point to 15.0.0 even though podSpec is pointing to 15.1.1

**Comment by poborin** [comment]
Hi @rezakhmf did you update cocoapods in your poject? You can do it by executing the following command in the application folder. It should be the same folder where `Podfile` is located. You can read more here: https://guides.cocoapods.org/using/using-cocoapods.html#when-to-use-pod-install-vs-pod-update
```
pod update
```
After that, your `Podfile.loc` should point to the latest `BluedotPointSDK`, unless there is a version restriction in the `Podfile`.

**Comment by poborin** [comment]
I assume we can mark it as Closed.
